import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/black.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/deadoralive.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/mod.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/ping.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/randomnumber.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/timeout.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/commands/userinfo.ts#0";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/events/interactionCreate.ts#1";
import "file:///C:/Users/Owner/Desktop/!rtsrs/src/events/ready.ts#1";